#!/usr/bin/env bash
# shellcheck disable=SC2034

set -e
# set -x

set -a
CRYSTAL_COMMAND=${CRYSTAL_COMMAND:-$(which crystal)}
SHARDS_COMMAND=${SHARDS_COMMAND:-$(which shards)}

CRYSTAL_VERSION=$(${CRYSTAL_COMMAND} --version | head -n 1 | cut -d \  -f 2)
LLVM_VERSION=$(${CRYSTAL_COMMAND} --version | grep LLVM: | cut -d \  -f 2)
SHARDS_VERSION=$(${SHARDS_COMMAND} --version | head -n 1 | cut -d \  -f 2)

GIT_REPO_CLEAN=$(git diff --exit-code > /dev/null 2>&1; echo $?)
GIT_TAG=$(git tag --merged HEAD | head -n 1)
GIT_REVISION=$(git rev-parse --short=12 HEAD)
GIT_BRANCH=$(git branch --show-current)
GIT_COMMIT_DATE=$(git show -s --format=%ci)
GIT_UNTRACKED=$(git ls-files --others --exclude-standard | grep -q '^.*$'; echo $?)

BUILD_TIME=$(date -u +"%FT%T.%NZ")
BUILD_USER=$USER
BUILD_ARGS="$*"
set +a

# 	docker run -u $UID:$GID -v $PWD:/src -it crystallang/crystal:latest-alpine sh -c "cd /src && shards build $@"
shards build "$@"
